---
title: "Title of the report"
author: Rakesh Poduval, `r Sys.Date()`
output:
  html_document: 
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: yeti
    highlight: monochrome
---

```{r template, echo = F}
htmltools::img(src = knitr::image_uri('RStudio-Ball.png'), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:0.2px;')
```

```{r setup, echo = F, include = F, cache = F}
# set global chunk options
knitr::opts_chunk$set(echo = F, comment = "", fig.width = 8, fig.heigth = 8)
options(width = 120, warn = -1)

# load packages and functions
library(knitr)
library(pander)

# load and prepare data

# Meta Info and internal functions

```

# Objective
Description of the document.

```{r , echo = F, include = F, cache = F}

```

# Heading 1

## Heading 1.1
```{r, message = F, }

```

## Heading 1.2
```{r, message = F}

```

# Heading 2

## Heading 2.1 
```{r, results = 'asis', message = F}

```

## Heading 2.2
```{r, results = 'asis', message = F}

```